# Generated by Django 3.2.4 on 2021-06-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210616_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='vip',
            name='vip_guahao',
            field=models.IntegerField(default=9, verbose_name='挂号折扣'),
        ),
        migrations.AddField(
            model_name='vip',
            name='vip_money',
            field=models.BigIntegerField(default=0, verbose_name='会员总金额'),
        ),
        migrations.AddField(
            model_name='vip',
            name='vip_money_least',
            field=models.BigIntegerField(default=0, verbose_name='会员余额'),
        ),
    ]
