# Generated by Django 3.2.4 on 2021-06-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210616_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip',
            name='vip_money_least',
            field=models.BigIntegerField(default=models.BigIntegerField(default=0, verbose_name='会员总金额'), verbose_name='会员余额'),
        ),
    ]
