# Generated by Django 3.2.4 on 2021-06-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_vip_vip_money_least'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip',
            name='vip_money',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='会员总金额'),
        ),
        migrations.AlterField(
            model_name='vip',
            name='vip_money_least',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10, verbose_name='会员余额'),
        ),
    ]
